import Mathlib.Tactic.Sat.FromLRAT

/-!
# Palomar probe: the encoding layer for kernel-checked SAT certificates (round 1)

A certificate for a KUM-family SAT claim has two halves:

1. `lrat_refutation foo cnf lrat` stores the (core) CNF as data, `foo.fmla : Sat.Fmla`, together
   with `foo.refute : Sat.Fmla.proof foo.fmla []`: no valuation satisfies it.  It calls Mathlib's
   `fromLRATAux`, so the kernel is the LRAT checker, but it skips the propositional statement that
   `lrat_proof` also builds.
2. `clause_witnesses foo.ws text` stores one witness per clause.  Each witness names the rule that
   produced the clause (a rank axiom, density, or a cyclic-order window), and `gen N w`
   regenerates the clause.  `fmlaBEq` checks, by kernel evaluation only, that the stored formula is
   exactly the regenerated one.

Round 1 measures the data layer only.  The matroid semantics (every generated clause holds for a
counterexample matroid) come next.

Variables follow `experiments/rank4_heavy_flat_splice/lean_witness.py`: DIMACS variable `4X + v`
means `r(X) ≥ v` for a bitmask `X` and `1 ≤ v ≤ 4`, and `from_lrat` shifts every index down by one.
-/

namespace Probe.Enc

open Lean Elab Command Term Meta

/-- Clause witnesses, mirroring the tokens written by `lean_witness.py`. -/
inductive W where
  | order (X v : ℕ)
  | cap (X v : ℕ)
  | dens (X k : ℕ)
  | mono (X a v : ℕ)
  | inc (X a v : ℕ)
  | sub (X a b v : ℕ)
  | win (s : List ℕ)

/-- Balanced `List.append` tree over `xs[lo:hi]`, so that long lists never nest deeply. -/
partial def balancedList (ty : Expr) (xs : Array Expr) (lo hi : Nat) : Expr :=
  if hi ≤ lo + 1 then
    mkApp3 (mkConst ``List.cons [levelZero]) ty xs[lo]! (mkApp (mkConst ``List.nil [levelZero]) ty)
  else
    let mid := (lo + hi) / 2
    mkApp3 (mkConst ``List.append [levelZero]) ty
      (balancedList ty xs lo mid) (balancedList ty xs mid hi)

/-- `lrat_refutation foo cnf lrat` adds `foo.fmla : Sat.Fmla` and
`foo.refute : Sat.Fmla.proof foo.fmla []`. -/
elab "lrat_refutation " n:ident ppSpace cnf:term:max ppSpace lrat:term:max : command => do
  let name := (← getCurrNamespace) ++ n.getId
  liftTermElabM do
    let cnf ← unsafe evalTerm String (mkConst ``String) cnf
    let lrat ← unsafe evalTerm String (mkConst ``String) lrat
    let (_, ctx, _, proof) ← Mathlib.Tactic.Sat.fromLRATAux cnf lrat name
    addDecl <| Declaration.defnDecl {
      name := name ++ `fmla, levelParams := [], type := mkConst ``Sat.Fmla, value := ctx
      hints := ReducibilityHints.abbrev, safety := DefinitionSafety.safe }
    addDecl <| Declaration.thmDecl {
      name := name ++ `refute, levelParams := []
      type := mkApp2 (mkConst ``Sat.Fmla.proof) (mkConst (name ++ `fmla))
        (mkConst ``Sat.Clause.nil)
      value := proof }

/-- `clause_witnesses foo text` adds `foo : List W`, parsed from `lean_witness.py` output. -/
elab "clause_witnesses " n:ident ppSpace src:term:max : command => do
  let name := (← getCurrNamespace) ++ n.getId
  liftTermElabM do
    let text ← unsafe evalTerm String (mkConst ``String) src
    let nat := fun (k : Nat) => mkRawNatLit k
    let mut ws : Array Expr := #[]
    for line in text.splitOn "\n" do
      match (line.splitOn " ").filter (· ≠ "") with
      | [] => pure ()
      | k :: rest =>
        let a := rest.map String.toNat!
        let e ← match k, a with
          | "o", [X, v] => pure <| mkApp2 (mkConst ``Probe.Enc.W.order) (nat X) (nat v)
          | "c", [X, v] => pure <| mkApp2 (mkConst ``Probe.Enc.W.cap) (nat X) (nat v)
          | "d", [X, v] => pure <| mkApp2 (mkConst ``Probe.Enc.W.dens) (nat X) (nat v)
          | "m", [X, x, v] => pure <| mkApp3 (mkConst ``Probe.Enc.W.mono) (nat X) (nat x) (nat v)
          | "i", [X, x, v] => pure <| mkApp3 (mkConst ``Probe.Enc.W.inc) (nat X) (nat x) (nat v)
          | "s", [X, x, y, v] => pure <| mkApp4 (mkConst ``Probe.Enc.W.sub) (nat X) (nat x) (nat y) (nat v)
          | "w", s => pure <| mkApp (mkConst ``Probe.Enc.W.win) (toExpr s)
          | _, _ => throwError "bad witness line: {line}"
        ws := ws.push e
    if ws.isEmpty then throwError "no witnesses"
    let ty : Expr := Lean.mkConst ``Probe.Enc.W
    addDecl <| Declaration.defnDecl {
      name, levelParams := [], type := mkApp (mkConst ``List [levelZero]) ty
      value := balancedList ty ws 0 ws.size
      hints := ReducibilityHints.abbrev, safety := DefinitionSafety.safe }

noncomputable section

/-- Lean index of DIMACS variable `4X + v`, i.e. of the statement `r(X) ≥ v`. -/
def idx (X v : ℕ) : ℕ := 4 * X + v - 1

/-- Bitmask of the length-4 window of the cyclic sequence `s` starting at position `i`. -/
def window (s : List ℕ) (i : ℕ) : ℕ :=
  (List.range 4).foldl (fun acc j => acc ||| 1 <<< s.getD ((i + j) % s.length) 0) 0

/-- The clause generated by a witness, literal for literal as in `lean_witness.py`. -/
def gen (N : ℕ) : W → List Sat.Literal
  | .order X v => [.neg (idx X (v + 1)), .pos (idx X v)]
  | .cap X v => [.neg (idx X v)]
  | .dens X k => [.pos (idx X k)]
  | .mono X a v => [.neg (idx X v), .pos (idx (X ||| 1 <<< a) v)]
  | .inc X a v => [.neg (idx (X ||| 1 <<< a) (v + 1)), .pos (idx X v)]
  | .sub X a b v =>
      [.neg (idx (X ||| 1 <<< a ||| 1 <<< b) v), .pos (idx (X ||| 1 <<< a) v),
        .pos (idx (X ||| 1 <<< b) v), .pos (idx X v)] ++
      (if 2 ≤ v then [.neg (idx X (v - 1))] else [])
  | .win s => (List.range N).map fun i => .neg (idx (window s i) 4)

/-- Number of elements of the bitmask `X` among the first `N`. -/
def pc (N X : ℕ) : ℕ := ((List.range N).filter fun j => X.testBit j).length

/-- Side conditions under which each generated clause is valid for a counterexample. -/
def valid (N : ℕ) : W → Bool
  | .order X v => decide (X < 2 ^ N ∧ 1 ≤ v ∧ v ≤ 3)
  | .cap X v => decide (X < 2 ^ N ∧ pc N X < v ∧ v ≤ 4)
  | .dens X k => decide (X < 2 ^ N ∧ 1 ≤ k ∧ k ≤ 4 ∧ N * (k - 1) < 4 * pc N X)
  | .mono X a v => decide (X < 2 ^ N ∧ a < N ∧ X.testBit a = false ∧ 1 ≤ v ∧ v ≤ 4)
  | .inc X a v => decide (X < 2 ^ N ∧ a < N ∧ X.testBit a = false ∧ 1 ≤ v ∧ v ≤ 3)
  | .sub X a b v => decide (X < 2 ^ N ∧ a < b ∧ b < N ∧ X.testBit a = false ∧
      X.testBit b = false ∧ 1 ≤ v ∧ v ≤ 4)
  | .win s => decide (s.length = N ∧ ∀ x < N, x ∈ s)

def litBEq : Sat.Literal → Sat.Literal → Bool
  | .pos a, .pos b => a == b
  | .neg a, .neg b => a == b
  | _, _ => false

def clauseBEq : List Sat.Literal → List Sat.Literal → Bool
  | [], [] => true
  | a :: c, b :: d => litBEq a b && clauseBEq c d
  | _, _ => false

def fmlaBEq : List (List Sat.Literal) → List (List Sat.Literal) → Bool
  | [], [] => true
  | c :: f, d :: g => clauseBEq c d && fmlaBEq f g
  | _, _ => false

end

theorem litBEq_eq {a b : Sat.Literal} (h : litBEq a b = true) : a = b := by
  cases a <;> cases b <;> simp_all [litBEq]

theorem clauseBEq_eq : ∀ {c d : List Sat.Literal}, clauseBEq c d = true → c = d
  | [], [], _ => rfl
  | [], _ :: _, h => by simp [clauseBEq] at h
  | _ :: _, [], h => by simp [clauseBEq] at h
  | _ :: _, _ :: _, h => by
    simp only [clauseBEq, Bool.and_eq_true] at h
    rw [litBEq_eq h.1, clauseBEq_eq h.2]

theorem fmlaBEq_eq : ∀ {f g : List (List Sat.Literal)}, fmlaBEq f g = true → f = g
  | [], [], _ => rfl
  | [], _ :: _, h => by simp [fmlaBEq] at h
  | _ :: _, [], h => by simp [fmlaBEq] at h
  | _ :: _, _ :: _, h => by
    simp only [fmlaBEq, Bool.and_eq_true] at h
    rw [clauseBEq_eq h.1, fmlaBEq_eq h.2]

end Probe.Enc
