import Probe.EncSound

/-!
# Encoding layer for KUM-type claims with side conditions

The KUM layer (`Enc.lean`, `EncSound.lean`) knows the rank axioms, density and cyclic-order
windows. The 10-element claims behind rank-4 KUM on 10 elements
(`experiments/rank4_heavy_flat_splice/lean_witness_f.py`) also use:

* `low X v`: `r(X) ≥ v`, where `v ≤ lowTab[|X|]` for a table of lower bounds by size (density,
  or the strict t=0 profile with no 6-plane and no 4-line);
* `fact X v b`: a listed fact about one set, `r(X) ≥ v` if `b` and `r(X) < v` otherwise (for
  example, that a given set is a flat of rank 3).

`RankModelF N lowTab facts` is an abstract rank function with these properties and no cyclic basis
ordering. A kernel-checked refutation of a formula regenerated from valid witnesses shows that no
such model exists (`no_modelF`).
-/

namespace Probe.Enc

open Lean Elab Command Term Meta

/-- Clause witnesses for claims with side conditions. -/
inductive WF where
  | order (X v : ℕ)
  | cap (X v : ℕ)
  | low (X v : ℕ)
  | mono (X a v : ℕ)
  | inc (X a v : ℕ)
  | sub (X a b v : ℕ)
  | fact (X v : ℕ) (b : Bool)
  | win (s : List ℕ)

/-- `f_witnesses foo text` adds `foo : List WF`, parsed from `lean_witness_f.py` output. -/
elab "f_witnesses " n:ident ppSpace src:term:max : command => do
  let name := (← getCurrNamespace) ++ n.getId
  liftTermElabM do
    let text ← unsafe evalTerm String (mkConst ``String) src
    let nat := fun (k : Nat) => mkRawNatLit k
    let mut ws : Array Expr := #[]
    for line in text.splitOn "\n" do
      match (line.splitOn " ").filter (· ≠ "") with
      | [] => pure ()
      | k :: rest =>
        let a := rest.map String.toNat!
        let e ← match k, a with
          | "o", [X, v] => pure <| mkApp2 (mkConst ``Probe.Enc.WF.order) (nat X) (nat v)
          | "c", [X, v] => pure <| mkApp2 (mkConst ``Probe.Enc.WF.cap) (nat X) (nat v)
          | "l", [X, v] => pure <| mkApp2 (mkConst ``Probe.Enc.WF.low) (nat X) (nat v)
          | "m", [X, x, v] => pure <| mkApp3 (mkConst ``Probe.Enc.WF.mono) (nat X) (nat x) (nat v)
          | "i", [X, x, v] => pure <| mkApp3 (mkConst ``Probe.Enc.WF.inc) (nat X) (nat x) (nat v)
          | "s", [X, x, y, v] =>
            pure <| mkApp4 (mkConst ``Probe.Enc.WF.sub) (nat X) (nat x) (nat y) (nat v)
          | "f", [X, v, b] =>
            pure <| mkApp3 (mkConst ``Probe.Enc.WF.fact) (nat X) (nat v) (toExpr (b == 1))
          | "w", s => pure <| mkApp (mkConst ``Probe.Enc.WF.win) (toExpr s)
          | _, _ => throwError "bad witness line: {line}"
        ws := ws.push e
    if ws.isEmpty then throwError "no witnesses"
    let ty : Expr := Lean.mkConst ``Probe.Enc.WF
    addDecl <| Declaration.defnDecl {
      name, levelParams := [], type := mkApp (mkConst ``List [Level.zero]) ty
      value := balancedList ty ws 0 ws.size
      hints := ReducibilityHints.abbrev, safety := DefinitionSafety.safe }

noncomputable section

/-- The clause generated by a witness. -/
def genF (N : ℕ) : WF → List Sat.Literal
  | .order X v => gen N (.order X v)
  | .cap X v => gen N (.cap X v)
  | .low X v => [.pos (idx X v)]
  | .mono X a v => gen N (.mono X a v)
  | .inc X a v => gen N (.inc X a v)
  | .sub X a b v => gen N (.sub X a b v)
  | .fact X v true => [.pos (idx X v)]
  | .fact X v false => [.neg (idx X v)]
  | .win s => gen N (.win s)

/-- Side conditions of the witnesses. -/
def validF (N : ℕ) (lowTab : List ℕ) (facts : List (ℕ × ℕ × Bool)) : WF → Bool
  | .order X v => valid N (.order X v)
  | .cap X v => valid N (.cap X v)
  | .low X v => decide (X < 2 ^ N ∧ 1 ≤ v ∧ v ≤ 4 ∧ v ≤ lowTab.getD (pc N X) 0)
  | .mono X a v => valid N (.mono X a v)
  | .inc X a v => valid N (.inc X a v)
  | .sub X a b v => valid N (.sub X a b v)
  | .fact X v b => decide (1 ≤ v ∧ v ≤ 4 ∧ (X, v, b) ∈ facts)
  | .win s => valid N (.win s)

end

/-- An abstract rank function with the properties the clauses use, and no cyclic basis
ordering. -/
structure RankModelF (N : ℕ) (lowTab : List ℕ) (facts : List (ℕ × ℕ × Bool)) where
  r : ℕ → ℕ
  card : ∀ X, X < 2 ^ N → r X ≤ pc N X
  low : ∀ X, X < 2 ^ N → lowTab.getD (pc N X) 0 ≤ r X
  mono : ∀ X a, X < 2 ^ N → a < N → X.testBit a = false → r X ≤ r (X ||| 1 <<< a)
  ins : ∀ X a, X < 2 ^ N → a < N → X.testBit a = false → r (X ||| 1 <<< a) ≤ r X + 1
  sub : ∀ X a b, X < 2 ^ N → a < b → b < N → X.testBit a = false → X.testBit b = false →
    r (X ||| 1 <<< a ||| 1 <<< b) + r X ≤ r (X ||| 1 <<< a) + r (X ||| 1 <<< b)
  factT : ∀ X v, (X, v, true) ∈ facts → v ≤ r X
  factF : ∀ X v, (X, v, false) ∈ facts → r X < v
  noCBO : ∀ s : List ℕ, s.length = N → (∀ x < N, x ∈ s) → (∀ x ∈ s, x < N) →
    ∃ i < N, r (window s i) < 4

section

variable {N : ℕ} {lowTab : List ℕ} {facts : List (ℕ × ℕ × Bool)}

/-- Variable `4X + v - 1` is true when `r(X) ≥ v`. -/
def valF (m : RankModelF N lowTab facts) : Sat.Valuation := fun i => i % 4 + 1 ≤ m.r (i / 4)

theorem valF_idx (m : RankModelF N lowTab facts) {v : ℕ} (h1 : 1 ≤ v) (h4 : v ≤ 4) (X : ℕ) :
    valF m (idx X v) ↔ v ≤ m.r X := by
  have hd : (4 * X + v - 1) / 4 = X := by omega
  have hm : (4 * X + v - 1) % 4 + 1 = v := by omega
  simp only [valF, idx, hd, hm]

/-- Every valid witness generates a clause satisfied by `valF m`. -/
theorem genF_sound (m : RankModelF N lowTab facts) :
    ∀ w, validF N lowTab facts w = true → (valF m).satisfies (genF N w)
  | .order X v, hv => by
    simp only [validF, valid, decide_eq_true_eq] at hv
    obtain ⟨_, h1, h3⟩ := hv
    simp only [genF, gen, Sat.Valuation.satisfies, Sat.Valuation.neg,
      valF_idx m (by omega : 1 ≤ v + 1) (by omega : v + 1 ≤ 4), valF_idx m h1 (by omega : v ≤ 4)]
    omega
  | .cap X v, hv => by
    simp only [validF, valid, decide_eq_true_eq] at hv
    obtain ⟨hX, hp, h4⟩ := hv
    have := m.card X hX
    simp only [genF, gen, Sat.Valuation.satisfies, Sat.Valuation.neg,
      valF_idx m (by omega : 1 ≤ v) h4]
    omega
  | .low X v, hv => by
    simp only [validF, decide_eq_true_eq] at hv
    obtain ⟨hX, h1, h4, hle⟩ := hv
    have := m.low X hX
    simp only [genF, Sat.Valuation.satisfies, Sat.Valuation.neg, valF_idx m h1 h4]
    omega
  | .mono X a v, hv => by
    simp only [validF, valid, decide_eq_true_eq] at hv
    obtain ⟨hX, ha, hb, h1, h4⟩ := hv
    have := m.mono X a hX ha hb
    simp only [genF, gen, Sat.Valuation.satisfies, Sat.Valuation.neg, valF_idx m h1 h4]
    omega
  | .inc X a v, hv => by
    simp only [validF, valid, decide_eq_true_eq] at hv
    obtain ⟨hX, ha, hb, h1, h3⟩ := hv
    have := m.ins X a hX ha hb
    simp only [genF, gen, Sat.Valuation.satisfies, Sat.Valuation.neg,
      valF_idx m (by omega : 1 ≤ v + 1) (by omega : v + 1 ≤ 4), valF_idx m h1 (by omega : v ≤ 4)]
    omega
  | .sub X a b v, hv => by
    simp only [validF, valid, decide_eq_true_eq] at hv
    obtain ⟨hX, hab, hbN, ha, hb, h1, h4⟩ := hv
    have := m.sub X a b hX hab hbN ha hb
    by_cases h2 : 2 ≤ v
    · simp only [genF, gen, h2, ↓reduceIte, List.cons_append, List.nil_append,
        Sat.Valuation.satisfies, Sat.Valuation.neg, valF_idx m h1 h4,
        valF_idx m (by omega : 1 ≤ v - 1) (by omega : v - 1 ≤ 4)]
      omega
    · simp only [genF, gen, h2, ↓reduceIte, List.append_nil,
        Sat.Valuation.satisfies, Sat.Valuation.neg, valF_idx m h1 h4]
      omega
  | .fact X v true, hv => by
    simp only [validF, decide_eq_true_eq] at hv
    obtain ⟨h1, h4, hmem⟩ := hv
    have := m.factT X v hmem
    simp only [genF, Sat.Valuation.satisfies, Sat.Valuation.neg, valF_idx m h1 h4]
    omega
  | .fact X v false, hv => by
    simp only [validF, decide_eq_true_eq] at hv
    obtain ⟨h1, h4, hmem⟩ := hv
    have := m.factF X v hmem
    simp only [genF, Sat.Valuation.satisfies, Sat.Valuation.neg, valF_idx m h1 h4]
    omega
  | .win s, hv => by
    simp only [validF, valid, decide_eq_true_eq] at hv
    obtain ⟨i, hi, hr⟩ := m.noCBO s hv.1 hv.2.1 hv.2.2
    refine (satisfies_map_neg (valF m) (List.range N) (fun i => idx (window s i) 4)).2 ?_
    intro hall
    have := (valF_idx m (by omega : 1 ≤ 4) (Nat.le_refl 4) (window s i)).1
      (hall i (List.mem_range.2 hi))
    omega

/-- A kernel-checked refutation of a formula regenerated from valid witnesses rules out every
rank model. -/
theorem no_modelF (m : RankModelF N lowTab facts) (f : Sat.Fmla) (hf : f.proof Sat.Clause.nil)
    (ws : List WF) (heq : (f : List (List Sat.Literal)) = ws.map (genF N))
    (hv : ws.all (validF N lowTab facts) = true) : False := by
  refine hf (valF m) ⟨fun c hc => ?_⟩
  rw [heq] at hc
  obtain ⟨w, hw, rfl⟩ := List.mem_map.1 hc
  exact genF_sound m w (List.all_eq_true.1 hv w hw)

end

end Probe.Enc
