import Probe.EncF

/-!
# Encoding layer for the hitting lemma on 14 elements

`experiments/rank4_heavy_flat_splice/lean_witness_h.py` writes the hitting lemma at `n = 14`
(`k = 3`), in the case of a 6-point line and no 9-point plane. Besides rank axioms, size bounds
(`low`) and facts (`fact`), as in `EncF.lean`, it has one clause per 4-set `B` (`hit B`):

  `B` is not a basis, or `E - B` contains a 3-set of rank at most 1, a 6-set of rank at most 2,
  or an 8-set of rank at most 3.

The subsets of `E - B` are listed by `combs`, in the order of Python's `itertools.combinations`.
`RankModelH` is an abstract rank function in which every such clause holds (`noDel`). The
matroid bridge obtains it from a matroid with no deletable basis.
-/

namespace Probe.Enc

open Lean Elab Command Term Meta

/-- The sublists of `l` of length `n`, in lexicographic order. -/
def combs : ℕ → List ℕ → List (List ℕ)
  | 0, _ => [[]]
  | _ + 1, [] => []
  | n + 1, x :: xs => (combs n xs).map (x :: ·) ++ combs (n + 1) xs

/-- The bitmask of a list of positions. -/
def maskOf (c : List ℕ) : ℕ := c.foldl (fun acc x => acc ||| 1 <<< x) 0

/-- The positions below `N` outside the bitmask `B`, in increasing order. -/
def restOf (N B : ℕ) : List ℕ := (List.range N).filter fun x => !B.testBit x

/-- Lower bounds on 14 elements: no loops, points `≤ 3`, lines `≤ 6`, and no 9-element plane. -/
def low14 : List ℕ := [0, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 4, 4, 4]

/-- Clause witnesses for the hitting claims. -/
inductive WH where
  | order (X v : ℕ)
  | cap (X v : ℕ)
  | low (X v : ℕ)
  | mono (X a v : ℕ)
  | inc (X a v : ℕ)
  | sub (X a b v : ℕ)
  | fact (X v : ℕ) (b : Bool)
  | hit (B : ℕ)

/-- `h_witnesses foo text` adds `foo : List WH`, parsed from `lean_witness_h.py` output. -/
elab "h_witnesses " n:ident ppSpace src:term:max : command => do
  let name := (← getCurrNamespace) ++ n.getId
  liftTermElabM do
    let text ← unsafe evalTerm String (Lean.mkConst ``String) src
    let nat := fun (k : Nat) => mkRawNatLit k
    let mut ws : Array Expr := #[]
    for line in text.splitOn "\n" do
      match (line.splitOn " ").filter (· ≠ "") with
      | [] => pure ()
      | k :: rest =>
        let a := rest.map String.toNat!
        let e ← match k, a with
          | "o", [X, v] => pure <| mkApp2 (Lean.mkConst ``Probe.Enc.WH.order) (nat X) (nat v)
          | "c", [X, v] => pure <| mkApp2 (Lean.mkConst ``Probe.Enc.WH.cap) (nat X) (nat v)
          | "l", [X, v] => pure <| mkApp2 (Lean.mkConst ``Probe.Enc.WH.low) (nat X) (nat v)
          | "m", [X, x, v] =>
            pure <| mkApp3 (Lean.mkConst ``Probe.Enc.WH.mono) (nat X) (nat x) (nat v)
          | "i", [X, x, v] =>
            pure <| mkApp3 (Lean.mkConst ``Probe.Enc.WH.inc) (nat X) (nat x) (nat v)
          | "s", [X, x, y, v] =>
            pure <| mkApp4 (Lean.mkConst ``Probe.Enc.WH.sub) (nat X) (nat x) (nat y) (nat v)
          | "f", [X, v, b] =>
            pure <| mkApp3 (Lean.mkConst ``Probe.Enc.WH.fact) (nat X) (nat v) (toExpr (b == 1))
          | "h", [B] => pure <| mkApp (Lean.mkConst ``Probe.Enc.WH.hit) (nat B)
          | _, _ => throwError "bad witness line: {line}"
        ws := ws.push e
    if ws.isEmpty then throwError "no witnesses"
    let ty : Expr := Lean.mkConst ``Probe.Enc.WH
    addDecl <| Declaration.defnDecl {
      name, levelParams := [], type := mkApp (Lean.mkConst ``List [Level.zero]) ty
      value := balancedList ty ws 0 ws.size
      hints := ReducibilityHints.abbrev, safety := DefinitionSafety.safe }

noncomputable section

/-- The clause generated by a witness. -/
def genH (N : ℕ) : WH → List Sat.Literal
  | .order X v => gen N (.order X v)
  | .cap X v => gen N (.cap X v)
  | .low X v => [.pos (idx X v)]
  | .mono X a v => gen N (.mono X a v)
  | .inc X a v => gen N (.inc X a v)
  | .sub X a b v => gen N (.sub X a b v)
  | .fact X v true => [.pos (idx X v)]
  | .fact X v false => [.neg (idx X v)]
  | .hit B => .neg (idx B 4) ::
      (((combs 3 (restOf N B)).map fun c => .neg (idx (maskOf c) 2)) ++
        (((combs 6 (restOf N B)).map fun c => .neg (idx (maskOf c) 3)) ++
          ((combs 8 (restOf N B)).map fun c => .neg (idx (maskOf c) 4))))

/-- Side conditions of the witnesses. -/
def validH (N : ℕ) (lowTab : List ℕ) (facts : List (ℕ × ℕ × Bool)) : WH → Bool
  | .order X v => valid N (.order X v)
  | .cap X v => valid N (.cap X v)
  | .low X v => decide (X < 2 ^ N ∧ 1 ≤ v ∧ v ≤ 4 ∧ v ≤ lowTab.getD (pc N X) 0)
  | .mono X a v => valid N (.mono X a v)
  | .inc X a v => valid N (.inc X a v)
  | .sub X a b v => valid N (.sub X a b v)
  | .fact X v b => decide (1 ≤ v ∧ v ≤ 4 ∧ (X, v, b) ∈ facts)
  | .hit B => decide (B < 2 ^ N ∧ pc N B = 4)

end

/-- An abstract rank function in which every 4-set of rank 4 leaves a dense-violating set. -/
structure RankModelH (N : ℕ) (lowTab : List ℕ) (facts : List (ℕ × ℕ × Bool)) where
  r : ℕ → ℕ
  card : ∀ X, X < 2 ^ N → r X ≤ pc N X
  low : ∀ X, X < 2 ^ N → lowTab.getD (pc N X) 0 ≤ r X
  mono : ∀ X a, X < 2 ^ N → a < N → X.testBit a = false → r X ≤ r (X ||| 1 <<< a)
  ins : ∀ X a, X < 2 ^ N → a < N → X.testBit a = false → r (X ||| 1 <<< a) ≤ r X + 1
  sub : ∀ X a b, X < 2 ^ N → a < b → b < N → X.testBit a = false → X.testBit b = false →
    r (X ||| 1 <<< a ||| 1 <<< b) + r X ≤ r (X ||| 1 <<< a) + r (X ||| 1 <<< b)
  factT : ∀ X v, (X, v, true) ∈ facts → v ≤ r X
  factF : ∀ X v, (X, v, false) ∈ facts → r X < v
  noDel : ∀ B, B < 2 ^ N → pc N B = 4 → 4 ≤ r B →
    (∃ c ∈ combs 3 (restOf N B), r (maskOf c) ≤ 1) ∨
    (∃ c ∈ combs 6 (restOf N B), r (maskOf c) ≤ 2) ∨
    (∃ c ∈ combs 8 (restOf N B), r (maskOf c) ≤ 3)

section

variable {N : ℕ} {lowTab : List ℕ} {facts : List (ℕ × ℕ × Bool)}

/-- Variable `4X + v - 1` is true when `r(X) ≥ v`. -/
def valH (m : RankModelH N lowTab facts) : Sat.Valuation := fun i => i % 4 + 1 ≤ m.r (i / 4)

theorem valH_idx (m : RankModelH N lowTab facts) {v : ℕ} (h1 : 1 ≤ v) (h4 : v ≤ 4) (X : ℕ) :
    valH m (idx X v) ↔ v ≤ m.r X := by
  have hd : (4 * X + v - 1) / 4 = X := by omega
  have hm : (4 * X + v - 1) % 4 + 1 = v := by omega
  simp only [valH, idx, hd, hm]

theorem satisfies_iff_not_all (w : Sat.Valuation) :
    ∀ c : List Sat.Literal, w.satisfies c ↔ ¬ ∀ l ∈ c, w.neg l
  | [] => by simp [Sat.Valuation.satisfies]
  | l :: c => by
    simp only [Sat.Valuation.satisfies, satisfies_iff_not_all w c, List.mem_cons,
      forall_eq_or_imp]
    tauto

/-- Every valid witness generates a clause satisfied by `valH m`. -/
theorem genH_sound (m : RankModelH N lowTab facts) :
    ∀ w, validH N lowTab facts w = true → (valH m).satisfies (genH N w)
  | .order X v, hv => by
    simp only [validH, valid, decide_eq_true_eq] at hv
    obtain ⟨_, h1, h3⟩ := hv
    simp only [genH, gen, Sat.Valuation.satisfies, Sat.Valuation.neg,
      valH_idx m (by omega : 1 ≤ v + 1) (by omega : v + 1 ≤ 4), valH_idx m h1 (by omega : v ≤ 4)]
    omega
  | .cap X v, hv => by
    simp only [validH, valid, decide_eq_true_eq] at hv
    obtain ⟨hX, hp, h4⟩ := hv
    have := m.card X hX
    simp only [genH, gen, Sat.Valuation.satisfies, Sat.Valuation.neg,
      valH_idx m (by omega : 1 ≤ v) h4]
    omega
  | .low X v, hv => by
    simp only [validH, decide_eq_true_eq] at hv
    obtain ⟨hX, h1, h4, hle⟩ := hv
    have := m.low X hX
    simp only [genH, Sat.Valuation.satisfies, Sat.Valuation.neg, valH_idx m h1 h4]
    omega
  | .mono X a v, hv => by
    simp only [validH, valid, decide_eq_true_eq] at hv
    obtain ⟨hX, ha, hb, h1, h4⟩ := hv
    have := m.mono X a hX ha hb
    simp only [genH, gen, Sat.Valuation.satisfies, Sat.Valuation.neg, valH_idx m h1 h4]
    omega
  | .inc X a v, hv => by
    simp only [validH, valid, decide_eq_true_eq] at hv
    obtain ⟨hX, ha, hb, h1, h3⟩ := hv
    have := m.ins X a hX ha hb
    simp only [genH, gen, Sat.Valuation.satisfies, Sat.Valuation.neg,
      valH_idx m (by omega : 1 ≤ v + 1) (by omega : v + 1 ≤ 4), valH_idx m h1 (by omega : v ≤ 4)]
    omega
  | .sub X a b v, hv => by
    simp only [validH, valid, decide_eq_true_eq] at hv
    obtain ⟨hX, hab, hbN, ha, hb, h1, h4⟩ := hv
    have := m.sub X a b hX hab hbN ha hb
    by_cases h2 : 2 ≤ v
    · simp only [genH, gen, h2, ↓reduceIte, List.cons_append, List.nil_append,
        Sat.Valuation.satisfies, Sat.Valuation.neg, valH_idx m h1 h4,
        valH_idx m (by omega : 1 ≤ v - 1) (by omega : v - 1 ≤ 4)]
      omega
    · simp only [genH, gen, h2, ↓reduceIte, List.append_nil,
        Sat.Valuation.satisfies, Sat.Valuation.neg, valH_idx m h1 h4]
      omega
  | .fact X v true, hv => by
    simp only [validH, decide_eq_true_eq] at hv
    obtain ⟨h1, h4, hmem⟩ := hv
    have := m.factT X v hmem
    simp only [genH, Sat.Valuation.satisfies, Sat.Valuation.neg, valH_idx m h1 h4]
    omega
  | .fact X v false, hv => by
    simp only [validH, decide_eq_true_eq] at hv
    obtain ⟨h1, h4, hmem⟩ := hv
    have := m.factF X v hmem
    simp only [genH, Sat.Valuation.satisfies, Sat.Valuation.neg, valH_idx m h1 h4]
    omega
  | .hit B, hv => by
    simp only [validH, decide_eq_true_eq] at hv
    obtain ⟨hB, hpc⟩ := hv
    rw [satisfies_iff_not_all]
    intro hall
    have hB4 : 4 ≤ m.r B :=
      (valH_idx m (by omega) (Nat.le_refl 4) B).1 (hall _ (List.mem_cons_self ..))
    rcases m.noDel B hB hpc hB4 with ⟨c, hc, hr⟩ | ⟨c, hc, hr⟩ | ⟨c, hc, hr⟩
    · have h := (valH_idx m (by omega : 1 ≤ 2) (by omega : 2 ≤ 4) (maskOf c)).1
        (hall _ (List.mem_cons.2 (Or.inr (List.mem_append.2 (Or.inl
          (List.mem_map.2 ⟨c, hc, rfl⟩))))))
      omega
    · have h := (valH_idx m (by omega : 1 ≤ 3) (by omega : 3 ≤ 4) (maskOf c)).1
        (hall _ (List.mem_cons.2 (Or.inr (List.mem_append.2 (Or.inr (List.mem_append.2
          (Or.inl (List.mem_map.2 ⟨c, hc, rfl⟩))))))))
      omega
    · have h := (valH_idx m (by omega : 1 ≤ 4) (Nat.le_refl 4) (maskOf c)).1
        (hall _ (List.mem_cons.2 (Or.inr (List.mem_append.2 (Or.inr (List.mem_append.2
          (Or.inr (List.mem_map.2 ⟨c, hc, rfl⟩))))))))
      omega

/-- A kernel-checked refutation of a formula regenerated from valid witnesses rules out every
rank model. -/
theorem no_modelH (m : RankModelH N lowTab facts) (f : Sat.Fmla) (hf : f.proof Sat.Clause.nil)
    (ws : List WH) (heq : (f : List (List Sat.Literal)) = ws.map (genH N))
    (hv : ws.all (validH N lowTab facts) = true) : False := by
  refine hf (valH m) ⟨fun c hc => ?_⟩
  rw [heq] at hc
  obtain ⟨w, hw, rfl⟩ := List.mem_map.1 hc
  exact genH_sound m w (List.all_eq_true.1 hv w hw)

end

end Probe.Enc
