import Probe.EncSound

/-!
# Encoding layer for the rank-4 extension theorem

The extension certificates (`experiments/rank4_heavy_flat_splice/ext_witness.py`) use positions
`0..3` for the basis `S` and `4..` for the elements `e_0, e_1, …` of a given ordering. Besides the
rank axioms their clauses say:

* `base X`: the set `X` (either `S` or an original 4-window) is a basis;
* `inter q`: for the merged sequence `q`, some window containing an element of `S` is not a
  basis.

`RankModelX` is an abstract rank function with exactly these properties. Its `noExt` field says
that no admissible merged sequence has all of its `S`-windows of rank 4. A merged sequence is
admissible (`interOK`) if:

* it is a permutation of the positions;
* every window avoiding `S` is one of the listed bases;
* for a linear sequence, it starts with `e_0, e_1, e_2` and ends with its last three elements.

The kernel checks admissibility for every witness, so the matroid bridge needs no reasoning about
list orders.
-/

namespace Probe.Enc

open Lean Elab Command Term Meta

/-- Clause witnesses for the extension certificates. -/
inductive WX where
  | order (X v : ℕ)
  | cap (X v : ℕ)
  | mono (X a v : ℕ)
  | inc (X a v : ℕ)
  | sub (X a b v : ℕ)
  | base (X : ℕ)
  | inter (q : List ℕ)

/-- `ext_witnesses foo text` adds `foo : List WX`, parsed from `ext_witness.py` output. -/
elab "ext_witnesses " n:ident ppSpace src:term:max : command => do
  let name := (← getCurrNamespace) ++ n.getId
  liftTermElabM do
    let text ← unsafe evalTerm String (mkConst ``String) src
    let nat := fun (k : Nat) => mkRawNatLit k
    let mut ws : Array Expr := #[]
    for line in text.splitOn "\n" do
      match (line.splitOn " ").filter (· ≠ "") with
      | [] => pure ()
      | k :: rest =>
        let a := rest.map String.toNat!
        let e ← match k, a with
          | "o", [X, v] => pure <| mkApp2 (mkConst ``Probe.Enc.WX.order) (nat X) (nat v)
          | "c", [X, v] => pure <| mkApp2 (mkConst ``Probe.Enc.WX.cap) (nat X) (nat v)
          | "m", [X, x, v] => pure <| mkApp3 (mkConst ``Probe.Enc.WX.mono) (nat X) (nat x) (nat v)
          | "i", [X, x, v] => pure <| mkApp3 (mkConst ``Probe.Enc.WX.inc) (nat X) (nat x) (nat v)
          | "s", [X, x, y, v] =>
            pure <| mkApp4 (mkConst ``Probe.Enc.WX.sub) (nat X) (nat x) (nat y) (nat v)
          | "b", [X] => pure <| mkApp (mkConst ``Probe.Enc.WX.base) (nat X)
          | "t", q => pure <| mkApp (mkConst ``Probe.Enc.WX.inter) (toExpr q)
          | _, _ => throwError "bad witness line: {line}"
        ws := ws.push e
    if ws.isEmpty then throwError "no witnesses"
    let ty : Expr := Lean.mkConst ``Probe.Enc.WX
    addDecl <| Declaration.defnDecl {
      name, levelParams := [], type := mkApp (mkConst ``List [Level.zero]) ty
      value := balancedList ty ws 0 ws.size
      hints := ReducibilityHints.abbrev, safety := DefinitionSafety.safe }

noncomputable section

/-- Window starts: every position of a cyclic sequence, or the full windows of a linear one. -/
def starts (cyc : Bool) (q : List ℕ) : List ℕ :=
  if cyc then List.range q.length else List.range (q.length - 3)

/-- The window starting at `j` contains a position of `S`. -/
def hasS (q : List ℕ) (j : ℕ) : Bool :=
  (List.range 4).any fun t => decide (q.getD ((j + t) % q.length) 0 < 4)

/-- The clause generated by a witness. -/
def genX (cyc : Bool) : WX → List Sat.Literal
  | .order X v => gen 0 (.order X v)
  | .cap X v => gen 0 (.cap X v)
  | .mono X a v => gen 0 (.mono X a v)
  | .inc X a v => gen 0 (.inc X a v)
  | .sub X a b v => gen 0 (.sub X a b v)
  | .base X => [.pos (idx X 4)]
  | .inter q => ((starts cyc q).filter (hasS q)).map fun j => .neg (idx (window q j) 4)

/-- An admissible merged sequence. -/
abbrev interOK (n : ℕ) (cyc : Bool) (bases : List ℕ) (q : List ℕ) : Prop :=
  q.length = n ∧ (∀ x < n, x ∈ q) ∧ (∀ x ∈ q, x < n) ∧
    (∀ j ∈ starts cyc q, hasS q j = false → window q j ∈ bases) ∧
    (cyc = false → q.take 3 = [4, 5, 6] ∧ q.drop (n - 3) = [n - 3, n - 2, n - 1])

/-- Side conditions of the witnesses. -/
def validX (n : ℕ) (cyc : Bool) (bases : List ℕ) : WX → Bool
  | .order X v => valid n (.order X v)
  | .cap X v => valid n (.cap X v)
  | .mono X a v => valid n (.mono X a v)
  | .inc X a v => valid n (.inc X a v)
  | .sub X a b v => valid n (.sub X a b v)
  | .base X => decide (X ∈ bases)
  | .inter q => decide (interOK n cyc bases q)

end

/-- An abstract rank function with the properties the extension clauses use. -/
structure RankModelX (n : ℕ) (cyc : Bool) (bases : List ℕ) where
  r : ℕ → ℕ
  card : ∀ X, X < 2 ^ n → r X ≤ pc n X
  mono : ∀ X a, X < 2 ^ n → a < n → X.testBit a = false → r X ≤ r (X ||| 1 <<< a)
  ins : ∀ X a, X < 2 ^ n → a < n → X.testBit a = false → r (X ||| 1 <<< a) ≤ r X + 1
  sub : ∀ X a b, X < 2 ^ n → a < b → b < n → X.testBit a = false → X.testBit b = false →
    r (X ||| 1 <<< a ||| 1 <<< b) + r X ≤ r (X ||| 1 <<< a) + r (X ||| 1 <<< b)
  base : ∀ X ∈ bases, 4 ≤ r X
  noExt : ∀ q, interOK n cyc bases q →
    ∃ j ∈ (starts cyc q).filter (hasS q), r (window q j) < 4

/-- Variable `4X + v - 1` is true when `r(X) ≥ v`. -/
def valX {n : ℕ} {cyc : Bool} {bases : List ℕ} (m : RankModelX n cyc bases) : Sat.Valuation :=
  fun i => i % 4 + 1 ≤ m.r (i / 4)

theorem valX_idx {n : ℕ} {cyc : Bool} {bases : List ℕ} (m : RankModelX n cyc bases) {v : ℕ}
    (h1 : 1 ≤ v) (h4 : v ≤ 4) (X : ℕ) : valX m (idx X v) ↔ v ≤ m.r X := by
  have hd : (4 * X + v - 1) / 4 = X := by omega
  have hm : (4 * X + v - 1) % 4 + 1 = v := by omega
  simp only [valX, idx, hd, hm]

/-- Every valid witness generates a clause satisfied by `valX m`. -/
theorem genX_sound {n : ℕ} {cyc : Bool} {bases : List ℕ} (m : RankModelX n cyc bases) :
    ∀ w, validX n cyc bases w = true → (valX m).satisfies (genX cyc w)
  | .order X v, hv => by
    simp only [validX, valid, decide_eq_true_eq] at hv
    obtain ⟨_, h1, h3⟩ := hv
    simp only [genX, gen, Sat.Valuation.satisfies, Sat.Valuation.neg,
      valX_idx m (by omega : 1 ≤ v + 1) (by omega : v + 1 ≤ 4), valX_idx m h1 (by omega : v ≤ 4)]
    omega
  | .cap X v, hv => by
    simp only [validX, valid, decide_eq_true_eq] at hv
    obtain ⟨hX, hp, h4⟩ := hv
    have := m.card X hX
    simp only [genX, gen, Sat.Valuation.satisfies, Sat.Valuation.neg,
      valX_idx m (by omega : 1 ≤ v) h4]
    omega
  | .mono X a v, hv => by
    simp only [validX, valid, decide_eq_true_eq] at hv
    obtain ⟨hX, ha, hb, h1, h4⟩ := hv
    have := m.mono X a hX ha hb
    simp only [genX, gen, Sat.Valuation.satisfies, Sat.Valuation.neg, valX_idx m h1 h4]
    omega
  | .inc X a v, hv => by
    simp only [validX, valid, decide_eq_true_eq] at hv
    obtain ⟨hX, ha, hb, h1, h3⟩ := hv
    have := m.ins X a hX ha hb
    simp only [genX, gen, Sat.Valuation.satisfies, Sat.Valuation.neg,
      valX_idx m (by omega : 1 ≤ v + 1) (by omega : v + 1 ≤ 4), valX_idx m h1 (by omega : v ≤ 4)]
    omega
  | .sub X a b v, hv => by
    simp only [validX, valid, decide_eq_true_eq] at hv
    obtain ⟨hX, hab, hbN, ha, hb, h1, h4⟩ := hv
    have := m.sub X a b hX hab hbN ha hb
    by_cases h2 : 2 ≤ v
    · simp only [genX, gen, h2, ↓reduceIte, List.cons_append, List.nil_append,
        Sat.Valuation.satisfies, Sat.Valuation.neg, valX_idx m h1 h4,
        valX_idx m (by omega : 1 ≤ v - 1) (by omega : v - 1 ≤ 4)]
      omega
    · simp only [genX, gen, h2, ↓reduceIte, List.append_nil,
        Sat.Valuation.satisfies, Sat.Valuation.neg, valX_idx m h1 h4]
      omega
  | .base X, hv => by
    simp only [validX, decide_eq_true_eq] at hv
    have := m.base X hv
    simp only [genX, Sat.Valuation.satisfies, Sat.Valuation.neg,
      valX_idx m (by omega : 1 ≤ 4) (Nat.le_refl 4)]
    omega
  | .inter q, hv => by
    simp only [validX, decide_eq_true_eq] at hv
    obtain ⟨j, hj, hr⟩ := m.noExt q hv
    refine (satisfies_map_neg (valX m) _ (fun j => idx (window q j) 4)).2 ?_
    intro hall
    have := (valX_idx m (by omega : 1 ≤ 4) (Nat.le_refl 4) (window q j)).1 (hall j hj)
    omega

/-- A kernel-checked refutation of a formula regenerated from valid witnesses rules out every
extension rank model. -/
theorem no_modelX {n : ℕ} {cyc : Bool} {bases : List ℕ} (m : RankModelX n cyc bases)
    (f : Sat.Fmla) (hf : f.proof Sat.Clause.nil) (ws : List WX)
    (heq : (f : List (List Sat.Literal)) = ws.map (genX cyc))
    (hv : ws.all (validX n cyc bases) = true) : False := by
  refine hf (valX m) ⟨fun c hc => ?_⟩
  rw [heq] at hc
  obtain ⟨w, hw, rfl⟩ := List.mem_map.1 hc
  exact genX_sound m w (List.all_eq_true.1 hv w hw)

end Probe.Enc
