import HigherRankKUM.Rank4.FourBlockPerm

namespace HigherRankKUM
namespace Rank4SevenTypeMoves

open Set
open Rank4FourBlockMove

noncomputable section

variable {α : Type*}

/-- Swap the first two coordinates of a four-block:
`[a,b,c,d] -> [b,a,c,d]`. -/
def adj01 : Equiv.Perm (Fin 4) :=
  Equiv.swap 0 1

/-- Swap the middle two coordinates:
`[a,b,c,d] -> [a,c,b,d]`. -/
def adj12 : Equiv.Perm (Fin 4) :=
  Equiv.swap 1 2

/-- Swap the last two coordinates:
`[a,b,c,d] -> [a,b,d,c]`. -/
def adj23 : Equiv.Perm (Fin 4) :=
  Equiv.swap 2 3

/-- Canonical cross-block move
`[a,b,c,d] -> [c,d,a,b]`. -/
def crossPairs : Equiv.Perm (Fin 4) :=
  (Equiv.swap 0 2).trans (Equiv.swap 1 3)

/-- Canonical asymmetric cross-block move
`[a,b,c,d] -> [c,d,b,a]`. -/
def crossPairsFlip : Equiv.Perm (Fin 4) :=
  (Equiv.swap 2 3).trans crossPairs

/-- Endpoint swap
`[a,b,c,d] -> [d,b,c,a]`. -/
def swap03 : Equiv.Perm (Fin 4) :=
  Equiv.swap 0 3

/-- The extra historical fixed-e repair generator
`[a,b,c,d] -> [a,d,c,b]`. -/
def swap13 : Equiv.Perm (Fin 4) :=
  Equiv.swap 1 3

/-- The seven generator types isolated by the exact/sampled fixed-e audits.

The move graph is treated as undirected downstream; the set of listed
generators itself need not be closed under inversion. -/
def generators : Set (Equiv.Perm (Fin 4)) :=
  {adj01, adj12, adj23, crossPairs, crossPairsFlip, swap03, swap13}

@[simp] theorem adj01_values :
    (adj01 0, adj01 1, adj01 2, adj01 3) = (1, 0, 2, 3) := by
  simp [adj01, Equiv.swap_apply_def]

@[simp] theorem adj12_values :
    (adj12 0, adj12 1, adj12 2, adj12 3) = (0, 2, 1, 3) := by
  simp [adj12, Equiv.swap_apply_def]

@[simp] theorem adj23_values :
    (adj23 0, adj23 1, adj23 2, adj23 3) = (0, 1, 3, 2) := by
  simp [adj23, Equiv.swap_apply_def]

@[simp] theorem crossPairs_values :
    (crossPairs 0, crossPairs 1, crossPairs 2, crossPairs 3) =
      (2, 3, 0, 1) := by
  simp [crossPairs, Equiv.swap_apply_def]

@[simp] theorem crossPairsFlip_values :
    (crossPairsFlip 0, crossPairsFlip 1,
      crossPairsFlip 2, crossPairsFlip 3) =
      (2, 3, 1, 0) := by
  simp [crossPairsFlip, crossPairs, Equiv.swap_apply_def]

@[simp] theorem swap03_values :
    (swap03 0, swap03 1, swap03 2, swap03 3) = (3, 1, 2, 0) := by
  simp [swap03, Equiv.swap_apply_def]

@[simp] theorem swap13_values :
    (swap13 0, swap13 1, swap13 2, swap13 3) = (0, 3, 2, 1) := by
  simp [swap13, Equiv.swap_apply_def]

/-- An undirected one-step move generated by one of the seven audited local
permutation types.

The second disjunct deliberately supplies the reverse edge even when the
listed generator is not an involution. This matches the computational state
graphs, where every accepted local reorder is an undirected adjacency. -/
def SevenTypeMove
    {E : Set α} {n : ℕ}
    (hn : 0 < n) (h4n : 4 ≤ n)
    (σ τ : Fin n ≃ E) : Prop :=
  ∃ (s : Fin n) (π : Equiv.Perm (Fin 4)),
    π ∈ generators ∧
      (τ = applyFourBlockPerm hn h4n σ s π ∨
       σ = applyFourBlockPerm hn h4n τ s π)

/-- The restricted seven-type move relation is symmetric by construction. -/
theorem SevenTypeMove.symm
    {E : Set α} {n : ℕ}
    {hn : 0 < n} {h4n : 4 ≤ n}
    {σ τ : Fin n ≃ E}
    (h : SevenTypeMove hn h4n σ τ) :
    SevenTypeMove hn h4n τ σ := by
  rcases h with ⟨s, π, hπ, hdir | hrev⟩
  · exact ⟨s, π, hπ, Or.inr hdir⟩
  · exact ⟨s, π, hπ, Or.inl hrev⟩

/-- Every seven-type move is, after forgetting the restricted generator label,
an ordinary four-block move. -/
theorem SevenTypeMove.fourBlockMove
    {E : Set α} {n : ℕ}
    {hn : 0 < n} {h4n : 4 ≤ n}
    {σ τ : Fin n ≃ E}
    (h : SevenTypeMove hn h4n σ τ) :
    FourBlockMove hn h4n σ τ := by
  rcases h with ⟨s, π, -, hdir | hrev⟩
  · exact ⟨s, π, hdir⟩
  · have hback : FourBlockMove hn h4n τ σ :=
      ⟨s, π, hrev⟩
    exact hback.symm

/-- CBO-preserving seven-type step. -/
def SevenTypeCBOStep
    (M : Matroid α) {E : Set α} {n : ℕ}
    (hn : 0 < n) (h4n : 4 ≤ n)
    (σ τ : Fin n ≃ E) : Prop :=
  CyclicBasisOrder M 4 hn σ ∧
  CyclicBasisOrder M 4 hn τ ∧
  SevenTypeMove hn h4n σ τ

theorem SevenTypeCBOStep.symm
    {M : Matroid α} {E : Set α} {n : ℕ}
    {hn : 0 < n} {h4n : 4 ≤ n}
    {σ τ : Fin n ≃ E}
    (h : SevenTypeCBOStep M hn h4n σ τ) :
    SevenTypeCBOStep M hn h4n τ σ := by
  exact ⟨h.2.1, h.1, h.2.2.symm⟩

/-- Seven-type fixed-e reachability. -/
def SevenTypeReachable
    (M : Matroid α) {E : Set α} {n : ℕ}
    (hn : 0 < n) (h4n : 4 ≤ n)
    (σ τ : Fin n ≃ E) : Prop :=
  Relation.ReflTransGen (SevenTypeCBOStep M hn h4n) σ τ

end

end Rank4SevenTypeMoves
end HigherRankKUM
